version: '3.7'

services:
  catalog.api:
    container_name: catalog-api
    image: phungdkh/catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/PhungDKH.Catalog.Api/Dockerfile
    networks:
      - phungdkh-brigde
    depends_on:
      - db1
      - rabbitmq
  ordering.api:
    container_name: ordering-api
    image: phungdkh/ordering-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    build:
      context: .
      dockerfile: Services/Ordering/PhungDKH.Ordering.Api/Dockerfile
    networks:
      - phungdkh-brigde
  identity.api:
    container_name: identity-api
    image: phungdkh/identity-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    build:
      context: .
      dockerfile: Services/Identity/PhungDKH.Identity.Api/Dockerfile
    networks: 
      - phungdkh-brigde
  apigateway.api:
    container_name: apigateway-api
    image: phungdkh/apigateway-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    build:
      context: .
      dockerfile: ApiGateway/PhungDKH.ApiGateway/Dockerfile
    networks: 
      - phungdkh-brigde
  db1:
    container_name: phungdkh-mssql-db
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - mssql-db-data:/var/opt/mssql
    networks:
      - phungdkh-brigde
  rabbitmq:
    container_name: phungdkh-rabbitmq
    image: rabbitmq:3.7-management  
    networks: 
      - phungdkh-brigde
  
volumes:
  mssql-db-data:

networks:
  phungdkh-brigde:
    driver: bridge
