version: '3.7'

services:
  catalog-api:
    container_name: catalog_api
    image: phungdkh/catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/PhungDKH.Catalog.Api/Dockerfile
    depends_on:
      - db1
      - rabbitmq
    networks:
      - phungdkh-network
  ordering-api:
    container_name: ordering_api
    image: phungdkh/ordering_api
    build:
      context: .
      dockerfile: Services/Ordering/PhungDKH.Ordering.Api/Dockerfile
    depends_on:
      - db1
      - rabbitmq
    networks:
      - phungdkh-network
  identity-api:
    container_name: identity_api
    image: phungdkh/identity_api
    build:
      context: .
      dockerfile: Services/Identity/PhungDKH.Identity.Api/Dockerfile
    depends_on:
      - db1
    networks: 
      - phungdkh-network
  apigateway-api:
    container_name: apigateway_api
    image: phungdkh/apigateway_api
    build:
      context: .
      dockerfile: ApiGateway/PhungDKH.ApiGateway/Dockerfile
    depends_on:
      - catalog-api
      - ordering-api
      - identity-api
    networks: 
      - phungdkh-network
  db1:
    container_name: phungdkh_mssql_db
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - mssql_db_data:/var/opt/mssql
    networks:
      - phungdkh-network
  rabbitmq:
    container_name: phungdkh_rabbitmq
    image: rabbitmq:3.7-management  
    networks: 
      - phungdkh-network
  
volumes:
  mssql_db_data:

networks:
  phungdkh-network:
    driver: bridge
    external: true
